# DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

In [1]:
!pip install ppscore

Requirement already satisfied: ppscore in c:\users\alia syed\anaconda3\lib\site-packages (1.3.1)
Requirement already satisfied: pandas>=1.0.0 in c:\users\alia syed\anaconda3\lib\site-packages (from ppscore) (1.4.2)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in c:\users\alia syed\anaconda3\lib\site-packages (from ppscore) (1.0.2)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\alia syed\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\alia syed\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\alia syed\anaconda3\lib\site-packages (from pandas>=1.0.0->ppscore) (1.21.5)
Requirement already satisfied: scipy>=1.1.0 in c:\users\alia syed\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.7.3)
Requirement already satisfied: joblib>=0.11 in c:\users\alia syed\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\alia syed\anaconda3\lib\site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\alia syed\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.0.0->ppscore) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.ensemble import IsolationForest

import ppscore as pps

In [3]:
df = pd.read_csv("adult_with_headers (1).csv")
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [5]:
df = df.replace(" ?", np.nan)

df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

# Encoding Techniques

In [6]:
for col in df.select_dtypes(include="object"):
    df[col].fillna(df[col].mode()[0], inplace=True)

In [7]:
for col in df.select_dtypes(include=np.number):
    df[col].fillna(df[col].median(), inplace=True)

In [8]:
num_cols = df.select_dtypes(include=np.number).columns

scaler = StandardScaler()
df_standard = df.copy()

df_standard[num_cols] = scaler.fit_transform(df_standard[num_cols])

df_standard.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,Male,0.148453,-0.21666,-0.035429,United-States,<=50K
1,0.837109,Self-emp-not-inc,-1.008707,Bachelors,1.134739,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145920,-0.21666,-2.222153,United-States,<=50K
2,-0.042642,Private,0.245079,HS-grad,-0.420060,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
3,1.057047,Private,0.425801,11th,-1.197459,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
4,-0.775768,Private,1.408176,Bachelors,1.134739,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145920,-0.21666,-0.035429,Cuba,<=50K

In [9]:
scaler = MinMaxScaler()

df_minmax = df.copy()

df_minmax[num_cols] = scaler.fit_transform(df_minmax[num_cols])

df_minmax.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

In [10]:
cat_cols = df.select_dtypes(include="object").columns
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [11]:
small_cat = [c for c in cat_cols if df[c].nunique() < 5]
small_cat

['sex', 'income']

In [12]:
df = pd.get_dummies(df, columns=small_cat)

In [13]:
large_cat = [c for c in cat_cols if c not in small_cat]
large_cat

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'native_country']

In [14]:
le = LabelEncoder()

for col in large_cat:
    df[col] = le.fit_transform(df[col])

In [15]:
df["capital_total"] = df["capital_gain"] + df["capital_loss"]

In [16]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[0,25,40,60,100],
    labels=[0,1,2,3]
)

In [17]:
df["age_group"] = df["age_group"].astype(int)

# Feature Engineering

In [18]:
df["capital_gain"] = np.log1p(df["capital_gain"])
df["capital_loss"] = np.log1p(df["capital_loss"])

In [19]:
iso = IsolationForest(contamination=0.01)

outliers = iso.fit_predict(df[num_cols])

df["outlier"] = outliers

df = df[df["outlier"] == 1]

df.drop("outlier", axis=1, inplace=True)

C:\Users\Alia syed\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [20]:
pps.matrix(df).head(20)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,age,age,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,age,workclass,0.000000,regression,True,mean absolute error,0.532600,0.627664,DecisionTreeRegressor()
2,age,fnlwgt,0.000000,regression,True,mean absolute error,76569.623800,77735.305833,DecisionTreeRegressor()
3,age,education,0.000000,regression,True,mean absolute error,2.710200,2.761682,DecisionTreeRegressor()
4,age,education_num,0.000000,regression,True,mean absolute error,1.863600,1.911727,DecisionTreeRegressor()
5,age,marital_status,0.151662,regression,True,mean absolute error,1.164800,0.988144,DecisionTreeRegressor()
6,age,occupation,0.003530,regression,True,mean absolute error,3.518200,3.505780,DecisionTreeRegressor()
7,age,relationship,0.004692,regression,True,mean absolute error,1.260800,1.254884,DecisionTreeRegressor()
8,age,race,0.000000,regression,True,mean absolute error,0.337600,0.575929,DecisionTreeRegressor()
9,age,capital_gain,0.000000,regression,True,mean absolute error,0.702925,1.276896,DecisionTreeRegressor()
10,age,capital_loss,0.000000,regression,True,mean absolute error,0.344059,0.653272,DecisionTreeRegressor()
11,age,hours_per_week,0.000000,regression,True,mean absolute error,7.090400,7.602853,DecisionTreeRegressor()
12,age,native_country,0.000000,regression,True,mean absolute error,1.618000,2.956147,DecisionTreeRegressor()
13,age,sex_ Female,0.000000,regression,True,mean absolute error,0.322600,0.432470,DecisionTreeRegressor()
14,age,sex_ Male,0.000000,regression,True,mean absolute error,0.322600,0.432470,DecisionTreeRegressor()
15,age,income_ <=50K,0.000000,regression,True,mean absolute error,0.233600,0.322135,DecisionTreeRegressor()
16,age,income_ >50K,0.000000,regression,True,mean absolute error,0.233600,0.322135,DecisionTreeRegressor()
17,age,capital_total,0.000000,regression,True,mean absolute error,1036.956400,1796.287878,DecisionTreeRegressor()
18,age,age_group,1.000000,regression,True,mean absolute error,0.682200,0.000000,DecisionTreeRegressor()
19,workclass,age,0.019483,regression,True,mean absolute error,11.074600,10.858838,DecisionTreeRegressor()

In [21]:
pps.predictors(df, y="income_ >50K")

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,income_ <=50K,income_ >50K,1.0,regression,True,mean absolute error,0.2336,0.000000,DecisionTreeRegressor()
1,age,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.322135,DecisionTreeRegressor()
2,workclass,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.350712,DecisionTreeRegressor()
3,fnlwgt,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.346417,DecisionTreeRegressor()
4,education,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.312099,DecisionTreeRegressor()
5,education_num,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.312099,DecisionTreeRegressor()
6,marital_status,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.293114,DecisionTreeRegressor()
7,occupation,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.324577,DecisionTreeRegressor()
8,relationship,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.290721,DecisionTreeRegressor()
9,race,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.355124,DecisionTreeRegressor()
10,capital_gain,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.298493,DecisionTreeRegressor()
11,capital_loss,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.331031,DecisionTreeRegressor()
12,hours_per_week,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.333425,DecisionTreeRegressor()
13,native_country,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.354347,DecisionTreeRegressor()
14,sex_ Female,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.345878,DecisionTreeRegressor()
15,sex_ Male,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.345878,DecisionTreeRegressor()
16,capital_total,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.269852,DecisionTreeRegressor()
17,age_group,income_ >50K,0.0,regression,True,mean absolute error,0.2336,0.328927,DecisionTreeRegressor()